/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SincronizarRouteImport } from './routes/sincronizar'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelIndexRouteImport } from './routes/painel.index'
import { Route as PainelAtribuicoesRouteImport } from './routes/painel.atribuicoes'
import { Route as PainelRuaRuaIdRouteImport } from './routes/painel.rua.$ruaId'
import { Route as PainelRuaRuaIdNovoRouteImport } from './routes/painel.rua.$ruaId_.novo'

const SincronizarRoute = SincronizarRouteImport.update({
  id: '/sincronizar',
  path: '/sincronizar',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelRoute,
} as any)
const PainelAtribuicoesRoute = PainelAtribuicoesRouteImport.update({
  id: '/atribuicoes',
  path: '/atribuicoes',
  getParentRoute: () => PainelRoute,
} as any)
const PainelRuaRuaIdRoute = PainelRuaRuaIdRouteImport.update({
  id: '/rua/$ruaId',
  path: '/rua/$ruaId',
  getParentRoute: () => PainelRoute,
} as any)
const PainelRuaRuaIdNovoRoute = PainelRuaRuaIdNovoRouteImport.update({
  id: '/rua/$ruaId_/novo',
  path: '/rua/$ruaId/novo',
  getParentRoute: () => PainelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/painel': typeof PainelRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/sincronizar': typeof SincronizarRoute
  '/painel/atribuicoes': typeof PainelAtribuicoesRoute
  '/painel/': typeof PainelIndexRoute
  '/painel/rua/$ruaId': typeof PainelRuaRuaIdRoute
  '/painel/rua/$ruaId/novo': typeof PainelRuaRuaIdNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/perfil': typeof PerfilRoute
  '/sincronizar': typeof SincronizarRoute
  '/painel/atribuicoes': typeof PainelAtribuicoesRoute
  '/painel': typeof PainelIndexRoute
  '/painel/rua/$ruaId': typeof PainelRuaRuaIdRoute
  '/painel/rua/$ruaId/novo': typeof PainelRuaRuaIdNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/painel': typeof PainelRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/sincronizar': typeof SincronizarRoute
  '/painel/atribuicoes': typeof PainelAtribuicoesRoute
  '/painel/': typeof PainelIndexRoute
  '/painel/rua/$ruaId': typeof PainelRuaRuaIdRoute
  '/painel/rua/$ruaId_/novo': typeof PainelRuaRuaIdNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/painel'
    | '/perfil'
    | '/sincronizar'
    | '/painel/atribuicoes'
    | '/painel/'
    | '/painel/rua/$ruaId'
    | '/painel/rua/$ruaId/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/perfil'
    | '/sincronizar'
    | '/painel/atribuicoes'
    | '/painel'
    | '/painel/rua/$ruaId'
    | '/painel/rua/$ruaId/novo'
  id:
    | '__root__'
    | '/'
    | '/painel'
    | '/perfil'
    | '/sincronizar'
    | '/painel/atribuicoes'
    | '/painel/'
    | '/painel/rua/$ruaId'
    | '/painel/rua/$ruaId_/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PainelRoute: typeof PainelRouteWithChildren
  PerfilRoute: typeof PerfilRoute
  SincronizarRoute: typeof SincronizarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sincronizar': {
      id: '/sincronizar'
      path: '/sincronizar'
      fullPath: '/sincronizar'
      preLoaderRoute: typeof SincronizarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/atribuicoes': {
      id: '/painel/atribuicoes'
      path: '/atribuicoes'
      fullPath: '/painel/atribuicoes'
      preLoaderRoute: typeof PainelAtribuicoesRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/rua/$ruaId': {
      id: '/painel/rua/$ruaId'
      path: '/rua/$ruaId'
      fullPath: '/painel/rua/$ruaId'
      preLoaderRoute: typeof PainelRuaRuaIdRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/rua/$ruaId_/novo': {
      id: '/painel/rua/$ruaId_/novo'
      path: '/rua/$ruaId/novo'
      fullPath: '/painel/rua/$ruaId/novo'
      preLoaderRoute: typeof PainelRuaRuaIdNovoRouteImport
      parentRoute: typeof PainelRoute
    }
  }
}

interface PainelRouteChildren {
  PainelAtribuicoesRoute: typeof PainelAtribuicoesRoute
  PainelIndexRoute: typeof PainelIndexRoute
  PainelRuaRuaIdRoute: typeof PainelRuaRuaIdRoute
  PainelRuaRuaIdNovoRoute: typeof PainelRuaRuaIdNovoRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelAtribuicoesRoute: PainelAtribuicoesRoute,
  PainelIndexRoute: PainelIndexRoute,
  PainelRuaRuaIdRoute: PainelRuaRuaIdRoute,
  PainelRuaRuaIdNovoRoute: PainelRuaRuaIdNovoRoute,
}

const PainelRouteWithChildren =
  PainelRoute._addFileChildren(PainelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PainelRoute: PainelRouteWithChildren,
  PerfilRoute: PerfilRoute,
  SincronizarRoute: SincronizarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
